### ISSUE TITLE
H2 width

### ISSUE THREAD

**Issue by mayard689** [WildCodeSchool/orleans-php-2003-project-aon#111]
H2 width to set to 85% to prevent return to new line in homepage.
Take care of what happens in mobile mode.

**Comment by mayard689** [comment]
The last clicked link is red in footer. This color must be set to "grey" as "normal" link. Visible on firefox.

**Comment by mayard689** [comment]
contact page : remove ":" after "pour nous écrire"

**Comment by mayard689** [comment]
contact page : create hierarchy to visually identify responsabilities and names/coordinates

**Comment by mayard689** [comment]
contact page : message object must be catch and display again if a problem occured

**Comment by mayard689** [comment]
contact page : error message for message object must be put under the input, not next. this make the field not large enought.

**Comment by mayard689** [comment]
contact page : remove the ":"
Add stars for all required field.

**Comment by mayard689** [comment]
contact page : prevent padding between error message and the input field

**Comment by mayard689** [comment]
stages : images size to check. The last image is to small and the text is too large on firefox. Size is ok with chromium.

**Comment by mayard689** [comment]
stage : remove ":" on the h1 title

**Comment by mayard689** [comment]
price page : there must not be white space under the footer if to few lines in the tab

**Comment by mayard689** [comment]
whoAreUs : the page height is to high with empty content. We must scroll aver a blank page to see the footer.
This problem see to be global to all pages but visible or not depending on the content size.

**Comment by mayard689** [comment]
homepage-mobile view : text is going out of the image. text is almost white on a non white picturee and white background.
Remove the text in mobile mode.

**Comment by mayard689** [comment]
homepage-mobile view : the event image must be centered horizontally

**Comment by mayard689** [comment]
homepage-mobile : hr margin must be set auto horizontally an 0 vertically

**Comment by mayard689** [comment]
homepage-mobile : the "voir tout nos activité" is not horizontally center. activity-button css code must be set to : margin: var(--margin-large) 0;

**Comment by mayard689** [comment]
contact page - mobile view : the text block on the bottoni s not repsonsive and get out of the page

**Comment by mayard689** [comment]
one "bulles" picture is not correctly spelled bulles25-3-l and not bulles23-3-3 on the general layout

**Comment by mayard689** [comment]
activity page : it is not responsive, if page screen width is lower than 350,the detail table get out of the page 

- desktop view, case no lesson is registered, text must be vertically centered

**Comment by mayard689** [comment]
Admin, lesson list view : lesson must be ordered according to activity title

**Comment by Emmanuelle-Mendels** [comment]
fait
